# Generated by Django 3.0.4 on 2020-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200314_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bulletin',
            field=models.CharField(choices=[('1', '신촌 안'), ('2', '신촌 밖')], default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('cp', '치킨&피자&햄버거'), ('bo', '분식'), ('ko', '한식'), ('jp', '일식'), ('et', '기타'), ('nh', '야식'), ('ch', '중식')], default='ko', max_length=100),
            preserve_default=False,
        ),
    ]
