# Generated by Django 3.0.4 on 2020-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200317_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('cp', '치킨&피자&햄버거'), ('bo', '분식'), ('ko', '한식'), ('et', '기타'), ('ch', '중식'), ('nh', '야식'), ('jp', '일식')], max_length=100),
        ),
    ]
