# Generated by Django 3.0.4 on 2020-03-18 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20200317_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('bo', '분식'), ('ko', '한식'), ('ch', '중식'), ('us', '양식'), ('et', '기타'), ('it', '이탈리안'), ('nh', '야식'), ('jp', '일식'), ('cp', '치킨&햄버거')], max_length=100),
        ),
    ]
