# Generated by Django 3.0.4 on 2020-03-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200318_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='hi', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='bulletin',
            field=models.CharField(choices=[('1', '신촌 안'), ('2', '신촌 밖')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('nh', '야식'), ('ch', '중식'), ('et', '기타'), ('jp', '일식'), ('bo', '분식'), ('ko', '한식'), ('us', '양식'), ('it', '이탈리안'), ('cp', '치킨&햄버거')], max_length=100),
        ),
    ]
