# Generated by Django 3.0.4 on 2020-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200321_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='bulletin',
            field=models.CharField(choices=[('2', '신촌 밖'), ('1', '신촌 안')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('bo', '분식'), ('ch', '중식'), ('jp', '일식'), ('et', '기타'), ('us', '양식'), ('cp', '치킨&햄버거'), ('it', '이탈리안'), ('nh', '야식'), ('ko', '한식')], max_length=100),
        ),
    ]
