# Generated by Django 3.0.4 on 2020-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200325_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('bo', '분식'), ('nh', '야식'), ('et', '기타'), ('jp', '일식'), ('it', '이탈리안'), ('ch', '중식'), ('us', '양식'), ('cp', '치킨&햄버거'), ('ko', '한식')], max_length=100),
        ),
    ]
